# Generated by Django 3.0.7 on 2020-06-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_auto_20200613_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='CISSOLD',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
