# Generated by Django 3.0.7 on 2020-06-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20200614_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityinfo',
            name='CQUANTITY',
        ),
        migrations.AddField(
            model_name='commodity',
            name='CQUANTITY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commodityinfo',
            name='SID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Market.Student'),
        ),
        migrations.CreateModel(
            name='StuStars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Market.Commodity')),
                ('SID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Market.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StuLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Market.Commodity')),
                ('SID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Market.Student')),
            ],
        ),
    ]
