# Generated by Django 3.0.7 on 2020-06-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StuOrg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticestu',
            name='SID',
        ),
        migrations.AddField(
            model_name='noticestu',
            name='SID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='StuOrg.Student'),
        ),
        migrations.RemoveField(
            model_name='orgcharge',
            name='SID',
        ),
        migrations.AddField(
            model_name='orgcharge',
            name='SID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='StuOrg.Student'),
        ),
        migrations.RemoveField(
            model_name='orgstu',
            name='SID',
        ),
        migrations.AddField(
            model_name='orgstu',
            name='SID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='StuOrg.Student'),
        ),
    ]
