# Generated by Django 3.0.7 on 2020-06-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StuOrg', '0002_auto_20200615_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='SID',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='noticestu',
            old_name='NID',
            new_name='notice',
        ),
        migrations.RenameField(
            model_name='noticestu',
            old_name='SID',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='orgcharge',
            old_name='OID',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='orgcharge',
            old_name='SID',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='orgstu',
            old_name='OID',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='orgstu',
            old_name='SID',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='SID',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='SADDRESS',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='SRATING',
        ),
    ]
