# Generated by Django 3.0.7 on 2020-06-20 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StuOrg', '0003_auto_20200620_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='student',
        ),
        migrations.AddField(
            model_name='notice',
            name='NTIME',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='StuOrg.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='OIMAGE',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='SINTRO',
            field=models.TextField(null=True),
        ),
    ]
