# Generated by Django 3.0.7 on 2020-06-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuOrg', '0004_auto_20200621_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='OIMAGE',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
